language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
notifications:
  email: false

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi 
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  #- export PATH=/home/travis/miniconda2/bin:$PATH
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then 
      source /home/travis/miniconda2/bin/activate root;
    else
      source /home/travis/miniconda3/bin/activate root;
    fi
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy cython pandas scipy pytest pytest-runner
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install dendropy
  - pip install coverage
  # - pip install python-igraph
  - conda update --yes pip
  - easy_install --upgrade distribute
  - python setup.py build_ext -i

# Run test
script:
#  - nosetests --with-cov --cover-test SuchTree
#  - coverage run --source=SuchTree setup.py test
  - python setup.py test

# Calculate coverage
after_success:
  - coveralls
